language: php

php:
  - 7.0
  - 7.1

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

before_install:
  - travis_retry composer self-update --stable -n

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o
  - cp .env.example .env
  - php artisan key:generate
#  - composer require satooshi/php-coveralls --dev

script:
  - composer run phpunit -- --coverage-clover ./tests/logs/clover.xml
  - composer run phpcs
  - composer run phpmd
  - composer run phpcpd

#after_script:
#  - php vendor/bin/coveralls -v
